### ISSUE TITLE
URLのリンクをクリックすると､ブラウザにて複数個のタブで開かれる

### ISSUE THREAD

**Issue by sk7z-xyz** [ayame-q/Tweetship#1]
中クリックでは4つ､左クリックでは8つ ブラウザの新しいタブでリンク先が開かれる

環境 Windows10 Home 1809
edge及びchromeで確認
Macは持っていないので不明

**Comment by sk7z-xyz** [comment]
訂正&追記:TweetShipを起動後 Ctrl+R等でリロードするとリロードした回数の2倍のタブが開かれる模様

**Comment by guraimasyousa** [comment]
MacBook Pro Retina 10.14.4 環境にて、同様の現象発生しました。
数えた限り、2,4,8のどれかで開かれます。起動直後は2個もしくは4の個同一タブが同時展開されますが、スリープ入った上で復帰した際には、4個もしくは8個のタブが展開されます。
これの条件分岐はなんともわかりませんが、起動時間が1つの要因かもしれないです。8時間ほどで開けた時と4時間ほどでの時で、開いているタブの数が違うような気がします。

**Comment by sk7z-xyz** [comment]
javascript全くわからないのでアレですが､リロードやスリープからの復帰でmainWindowをロードする際に､以前のイベントリスナーを解除せずに追加でイベントリスナーが登録されている感じがします

**Comment by ayame-q** [comment]
ご報告ありがとうございます。
確認が遅くなってごめんなさい。

なぜかmacOSでデフォルトブラウザをSafariに設定していると起きないようで、全く気づきませんでした。
Chromeをデフォルトブラウザに変更したら再現したので頑張って修正します。

**Comment by ayame-q** [comment]
修正しました。
ページをリロードするたびにイベントが登録してしまっていたいたのが原因でした。
