### ISSUE TITLE
画像をクリックすると、TweetDeck側が青く潰れる

### ISSUE THREAD

**Issue by guraimasyousa** [ayame-q/Tweetship#2]
更新を行ったところ、リンクは1つで開くようになったのですが、今度はTweetDeck側がブルーになって閲覧できなくなりました。
リロードすれば問題なく閲覧できますが、ちょっとこれだと不便かと…
Winではまだ未検証ですが、Chromeへのリンクだけが変なのはなんででしょうね…

OS：MacBook Pro Retina 10.14.4 
リンク先：Google Chrome 75.0.3770.100（Official Build）（64 ビット）

**Comment by guraimasyousa** [comment]
すみません。正確には、画像をクリックするとでした。タイトルも修正します。

**Comment by ayame-q** [comment]
ご報告ありがとうございます。
Electronの最新バージョン(v5.0.5/v5.0.6)に起因する問題のようでしたので、場当たり的対応ですがElectronのバージョンダウンにて対応しました。
